export const ROUTES = {
  HOME: { path: "/", label: "HOME" },
  HISTORY: { path: "/history", label: "역대 당첨 회차 확인" },
  NUMBER_GENERATION: { path: "/number-generation", label: "행운의 번호 생성" },
  S_NUMBER_GENERATION: {
    path: "/s-number-generation",
    label: "당첨 시뮬레이션",
  },
  WINNING_STORES: { path: "/winning-stores", label: "당첨 매장 찾기" },
  ALL_STORES: { path: "/all-stores", label: "로또 판매점 찾기" },
  STATISTIC: { path: "/statistic", label: "로또 DATA" },
  SIMULATION_RESULT: { path: "/s-result", label: "" },
  RESULT: { path: "/result", label: "" },
  HISTORY_DETAIL: { path: "/history/:drawNumber", label: "" },
  CALLBACK: { path: "/auth/:provider/callback", label: "" },
  // LOGIN: { path: "/login", label: "" },
  SIGNUP: { path: "/signup", label: "회원가입" },
  LOGIN: { path: "/login", label: "로그인" },
  UPDATE_PROFILE: { path: "/update-profile", label: "회원정보 수정" },
  RESET_PASSWORD: { path: "/reset-password", label: "비밀번호 재설정" },
  EMAIL_VERIFICATION: { path: "/email-verification", label: "이메일 인증" },
  // SAVED_COMBINATIONS: { path: "/saved-combinations", label: "내 번호" },
};
