export const ROUTES = {
  HOME: { path: "/", label: "HOME" },
  HISTORY: { path: "/history", label: "역대 당첨 회차 확인" },
  NUMBER_GENERATION: { path: "/number-generation", label: "행운의 번호 생성" },
  WINNING_STORES: { path: "/winning-stores", label: "당첨 매장 찾기" },
  ALL_STORES: { path: "/all-stores", label: "로또 판매점 찾기" },
  STATISTIC: { path: "/statistic", label: "로또 DATA" },
  RESULT: { path: "/result", label: "" },
  HISTORY_DETAIL: { path: "/history/:drawNumber", label: "" },
  SIGNUP: { path: "/signup", label: "" },
  LOGIN: { path: "/login", label: "" },
  UPDATE_PROFILE: { path: "/update-profile", label: "" },
  FIND_PASSWORD: { path: "/find-password", label: "" },
  MYPAGE: { path: "/mypgae", label: "" },
  DELETE_ACCOUNT: { path: "/delete-account", label: "" },
  DASHBOARD: { path: "/dashboard", label: "" },
  SAVED_NUMBERS: { path: "/saved-numbers", label: "" },
};
